Task 1

In [1]:
import numpy as np

sensor_data = np.array([
    [12, 15, 14, 10, 13],
    [20, 22, 19, 18, 21],
    [30, 28, 27, 29, 31],
    [25, 24, 26, 23, 22]
])

avg_per_machine = np.mean(sensor_data, axis=1)
print("Average per machine:", avg_per_machine)

max_per_column = np.max(sensor_data, axis=0)
print("Max per time interval:", max_per_column)

normalized_data = sensor_data / max_per_column
print("Normalized Matrix:\n", normalized_data)

machines_above_20 = np.where(avg_per_machine > 20)[0]
print("Machines with avg > 20 (index):", machines_above_20)

reshaped_matrix = sensor_data.reshape(2, 10)
print("Reshaped Matrix (2x10):\n", reshaped_matrix)

Average per machine: [12.8 20.  29.  24. ]
Max per time interval: [30 28 27 29 31]
Normalized Matrix:
 [[0.4        0.53571429 0.51851852 0.34482759 0.41935484]
 [0.66666667 0.78571429 0.7037037  0.62068966 0.67741935]
 [1.         1.         1.         1.         1.        ]
 [0.83333333 0.85714286 0.96296296 0.79310345 0.70967742]]
Machines with avg > 20 (index): [2 3]
Reshaped Matrix (2x10):
 [[12 15 14 10 13 20 22 19 18 21]
 [30 28 27 29 31 25 24 26 23 22]]


Task 3

In [2]:
import numpy as np

A = np.random.randint(1, 51, (3, 3))
B = np.random.randint(1, 51, (3, 3))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

matrix_mult = A @ B
print("Matrix Multiplication (A @ B):\n", matrix_mult)

elementwise_mult = A * B
print("Element-wise Multiplication:\n", elementwise_mult)

greater_than_100 = matrix_mult[matrix_mult > 100]
print("Elements > 100:\n", greater_than_100)

A[A < 10] = 0
B[B < 10] = 0

print("Matrix A after replacing <10:\n", A)
print("Matrix B after replacing <10:\n", B)

stacked_matrix = np.vstack((A, B))
print("Vertically Stacked Matrix:\n", stacked_matrix)

Matrix A:
 [[19 15 36]
 [21  3 35]
 [16  8 13]]
Matrix B:
 [[27  9 12]
 [50  9 11]
 [12 31 13]]
Matrix Multiplication (A @ B):
 [[1695 1422  861]
 [1137 1301  740]
 [ 988  619  449]]
Element-wise Multiplication:
 [[ 513  135  432]
 [1050   27  385]
 [ 192  248  169]]
Elements > 100:
 [1695 1422  861 1137 1301  740  988  619  449]
Matrix A after replacing <10:
 [[19 15 36]
 [21  0 35]
 [16  0 13]]
Matrix B after replacing <10:
 [[27  0 12]
 [50  0 11]
 [12 31 13]]
Vertically Stacked Matrix:
 [[19 15 36]
 [21  0 35]
 [16  0 13]
 [27  0 12]
 [50  0 11]
 [12 31 13]]
